#!/bin/env bash

set -euo pipefail

mkdir -p badges

# Versions badge with Python versions that we run tests against
uv run --with pybadges --with setuptools -m pybadges --left-text Python --right-color blue --right-text '3.10 | 3.11 | 3.12 | 3.13 | 3.14'  > badges/python-versions.svg

# Coverage badge
uv sync --dev --all-extras
uv run --with coverage coverage run --source rfc3230_digest_headers -m pytest -v tests/
uv run --with coverage coverage report -m
COVERAGE_PERCENT=$(uv run --with coverage coverage json --pretty-print -o - | jq '.totals.percent_covered_display' | tr -d '"%')
uv run --with pybadges --with setuptools -m pybadges --left-text Coverage --right-color green --right-text "${COVERAGE_PERCENT}%" > badges/coverage.svg
